export type LanguageMedium =
  | "ENGLISH MEDIUM"
  | "SINHALA MEDIUM"
  | "TAMIL MEDIUM";

export type EduLevel = "A/L" | "O/L";

export type AlSubjectStream =
  | "PHYSICAL SCIENCE STREAM"
  | "BIO SCIENCE STREAM"
  | "COMMERCE STREAM"
  | "ARTS STREAM"
  | "TECHNOLOGY STREAM";

export type PhysicalScienceSubjects =
  | "PURE MATHEMATICS"
  | "APPLIED MATHEMATICS"
  | "PHYSICS"
  | "CHEMISTRY";

export type BioScienceSubjects = "BIOLOGY" | "PHYSICS" | "CHEMISTRY";

export type CommerceSubjects =
  | "BUSINESS STUDIES"
  | "ACCOUNTING"
  | "ECONOMICS"
  | "ICT"
  | "BUSINESS STATISTICS"
  | "ENGLISH LITERATURE"
  | "POLITICAL SCIENCE";

export type ArtSubjects =
  | "SINHALA"
  | "LOGIC"
  | "POLITICAL SCIENCE"
  | "GEOGRAPHY"
  | "BUDDHIST CIVILIZATION"
  | "ENGLISH LITERARTURE"
  | "JAPANESE"
  | "HISTORY"
  | "DRAMA";

export type TechnologySubjects =
  | "ENGINEERING TECHNOLOGY"
  | "SCIENCE FOR TECHNOLOGY"
  | "MATHEMATICS"
  | "ICT"
  | "BIO SYSTEMS TECHNOLOGY"
  | "AGRICULTURE";

export type OlFirstCategory =
  | "BUSINESS & ACCOUNTING STUDIES"
  | "GEOGRAPHY"
  | "CIVIC EDUCATION"
  | "ENTREPRENEURSHIP STUDIES"
  | "SECOND LANGUAGE - SINHALA (FOR STUDENTS WHOSE DOMINANT LANGUAGE IS TAMIL)"
  | "SECOND LANGUAGE - TAMIL (FOR STUDENTS WHOSE DOMINANT LANGUAGE IS SINHALA)"
  | "PALI LANGUAGE"
  | "SANSKRIT LANGUAGE"
  | "FRENCH LANGUAGE"
  | "GERMAN LANGUAGE"
  | "HINDI LANGUAGE"
  | "JAPANESE LANGUAGE"
  | "ARABIC LANGUAGE"
  | "KOREAN LANGUAGE"
  | "CHINESE LANGUAGE"
  | "RUSSIAN LANGUAGE";

export type OlSecondCategory =
  | "EASTERN MUSIC"
  | "WESTERN MUSIC"
  | "CARNATIC MUSIC"
  | "EASTERN DANCING"
  | "BHARATHA DANCING"
  | "ART"
  | "APPRECIATION OF ENGLISH LITERARY TEXTS (ENGLISH LITERATURE)"
  | "APPRECIATION OF SINHALA LITERARY TEXTS (SINHALA LITERATURE)"
  | "APPRECIATION OF TAMIL LITERARY TEXTS (TAMIL LITERATURE)"
  | "APPRECIATION OF ARABIC LITERARY TEXTS (ARABIC LITERATURE)"
  | "DRAMA AND THEATRE";

export type OlThirdCategory =
  | "INFORMATION & COMMUNICATION TECHNOLOGY"
  | "AGRICULTURE & FOOD TECHNOLOGY"
  | "AQUATIC BIO RESOURCES TECHNOLOGY"
  | "ARTS & CRAFTS"
  | "HOME ECONOMICS"
  | "HEALTH & PHYSICAL EDUCATION"
  | "COMMUNICATION & MEDIA STUDIES"
  | "DESIGN & CONSTRUCTION TECHNOLOGY"
  | "DESIGN & MECHANICAL TECHNOLOGY"
  | "DESIGN, ELECTRICAL & ELECTRONIC TECHNOLOGY"
  | "ELECTRONIC WRITING & SHORTHAND";

export type OlSubjcts =
  | OlFirstCategory
  | OlSecondCategory
  | OlThirdCategory
  | "SINHALA LANGUAGE"
  | "TAMIL LANGUAGE "
  | "ENGLISH LANGUAGE"
  | "MATHEMATICS"
  | "SCIENCE"
  | "HISTORY"
  | "BUDDHISM"
  | "HINDUISM"
  | "ISLAM"
  | "CHRISTIANITY";
