export type LanguageMedium =
  | "ENGLISH MEDIUM"
  | "SINHALA MEDIUM"
  | "TAMIL MEDIUM";

export type EduLevel = "A/L" | "O/L";

export type AlSubjectStream =
  | "PHYSICAL SCIENCE STREAM"
  | "BIO SCIENCE STREAM"
  | "COMMERCE STREAM"
  | "ARTS STREAM"
  | "TECHNOLOGY STREAM";

export type OlFirstCategory =
  | "BUSINESS & ACCOUNTING STUDIES"
  | "GEOGRAPHY"
  | "CIVIC EDUCATION"
  | "ENTREPRENEURSHIP STUDIES"
  | "SECOND LANGUAGE - SINHALA (FOR STUDENTS WHOSE DOMINANT LANGUAGE IS TAMIL)"
  | "SECOND LANGUAGE - TAMIL (FOR STUDENTS WHOSE DOMINANT LANGUAGE IS SINHALA)"
  | "PALI LANGUAGE"
  | "SANSKRIT LANGUAGE"
  | "FRENCH LANGUAGE"
  | "GERMAN LANGUAGE"
  | "HINDI LANGUAGE"
  | "JAPANESE LANGUAGE"
  | "ARABIC LANGUAGE"
  | "KOREAN LANGUAGE"
  | "CHINESE LANGUAGE"
  | "RUSSIAN LANGUAGE";

export type OlSecondCategory =
  | "EASTERN MUSIC"
  | "WESTERN MUSIC"
  | "CARNATIC MUSIC"
  | "EASTERN DANCING"
  | "BHARATHA DANCING"
  | "ART"
  | "APPRECIATION OF ENGLISH LITERARY TEXTS (ENGLISH LITERATURE)"
  | "APPRECIATION OF SINHALA LITERARY TEXTS (SINHALA LITERATURE)"
  | "APPRECIATION OF TAMIL LITERARY TEXTS (TAMIL LITERATURE)"
  | "APPRECIATION OF ARABIC LITERARY TEXTS (ARABIC LITERATURE)"
  | "DRAMA AND THEATRE";

export type OlThirdCategory =
  | "INFORMATION & COMMUNICATION TECHNOLOGY"
  | "AGRICULTURE & FOOD TECHNOLOGY"
  | "AQUATIC BIO RESOURCES TECHNOLOGY"
  | "ARTS & CRAFTS"
  | "HOME ECONOMICS"
  | "HEALTH & PHYSICAL EDUCATION"
  | "COMMUNICATION & MEDIA STUDIES"
  | "DESIGN & CONSTRUCTION TECHNOLOGY"
  | "DESIGN & MECHANICAL TECHNOLOGY"
  | "DESIGN, ELECTRICAL & ELECTRONIC TECHNOLOGY"
  | "ELECTRONIC WRITING & SHORTHAND";
